#!/bin/bash

cat << EOF > pyscript.py
#!/usr/bin/python3

try:
    print($1.__doc__)
except NameError:
    import $(cut -d'.' -f1 <<< $1)
    print($1.__doc__)
   
EOF

chmod 755 pyscript.py

./pyscript.py